export const ErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  ISSUE_NOT_FOUND: 'ISSUE_NOT_FOUND',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  SLUG_TAKEN: 'SLUG_TAKEN',
  MEMBER_ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  FILTER_NOT_FOUND: 'FILTER_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
} as const;
