export const ErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  ISSUE_NOT_FOUND: 'ISSUE_NOT_FOUND',
} as const;
